# Generated by Django 3.1 on 2020-08-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20200820_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='dificulty',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
