# Generated by Django 3.1 on 2020-08-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_class_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
