# Generated by Django 3.1 on 2020-08-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20200824_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='time',
            field=models.CharField(blank=True, choices=[('1', '06:00'), ('2', '08:00'), ('3', '12:00'), ('4', '18:00'), ('5', '20:00')], max_length=10, null=True),
        ),
    ]
