# Generated by Django 3.1 on 2020-08-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.IntegerField(choices=[(1, '5 Day Meditation in Morocco'), (2, '7 Day Authentic Yoga Retreat in Ireland'), (3, '5 Day Authentic Yoga in Italy'), (4, 'Surf & yoga in Ireland'), (5, 'Hatha Yoga'), (6, 'Yoga 4 Beginners'), (7, 'Ashtanga Yoga'), (8, 'Vinyasa yoga'), (9, 'Iyengar Yoga')]),
        ),
    ]
