# Generated by Django 3.1 on 2020-08-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.CharField(choices=[('5 Day Meditation in Morocco', '5 Day Meditation in Morocco'), ('7 Day Authentic Yoga Retreat in Ireland', '7 Day Authentic Yoga Retreat in Ireland'), ('5 Day Authentic Yoga in Italy', '5 Day Authentic Yoga in Italy'), ('Surf & yoga in Ireland', 'Surf & yoga in Ireland'), ('Hatha Yoga', 'Hatha Yoga'), ('Yoga 4 Beginners', 'Yoga 4 Beginners'), ('Ashtanga Yoga', 'Ashtanga Yoga'), ('Vinyasa yoga', 'Vinyasa yoga'), ('Iyengar Yoga', 'Iyengar Yoga')], max_length=200),
        ),
    ]
