# Generated by Django 3.1 on 2020-08-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retreats', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
